import Config

# Configure your database
config :droodotfoo, Droodotfoo.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "droodotfoo_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  types: Droodotfoo.PostgresTypes

# Oban queues for development (increased concurrency for better throughput)
config :droodotfoo, Oban,
  queues: [ingestion: 5, images: 4, backups: 1, embeddings: 2, notifications: 2],
  plugins: [
    Oban.Plugins.Pruner,
    {Oban.Plugins.Cron,
     crontab: [
       # OSRS Wiki sync every 15 minutes
       {"*/15 * * * *", Droodotfoo.Wiki.Ingestion.OSRSSyncWorker},
       # nLab sync daily at 4am
       {"0 4 * * *", Droodotfoo.Wiki.Ingestion.NLabSyncWorker},
       # VintageMachinery sync weekly on Sunday at 2am
       {"0 2 * * 0", Droodotfoo.Wiki.Ingestion.VintageMachinerySyncWorker},
       # Wikipedia refresh weekly on Saturday at 2am
       {"0 2 * * 6", Droodotfoo.Wiki.Ingestion.WikipediaSyncWorker},
       # Cross-source link detection daily at 5am (after syncs)
       {"0 5 * * *", Droodotfoo.Wiki.CrossLinkWorker},
       # PostgreSQL backup daily at 3am
       {"0 3 * * *", Droodotfoo.Wiki.Backup.PostgresWorker},
       # Embedding refresh nightly at 6am (after all syncs complete)
       {"0 6 * * *", Droodotfoo.Wiki.EmbeddingWorker}
     ]}
  ]

# Ollama for local development (run: ollama serve)
config :droodotfoo, Droodotfoo.Wiki.Ollama,
  base_url: System.get_env("OLLAMA_URL", "http://localhost:11434"),
  model: "nomic-embed-text",
  timeout: 60_000

# MediaWiki client for development
config :droodotfoo, Droodotfoo.Wiki.Ingestion.MediaWikiClient,
  base_url: "https://oldschool.runescape.wiki/api.php",
  user_agent: "DrooFoo-WikiMirror/1.0 (https://droo.foo; dev@droo.foo)",
  rate_limit_ms: 1_000

# nLab client for development
config :droodotfoo, Droodotfoo.Wiki.Ingestion.NLabClient,
  repo_url: "https://github.com/ncatlab/nlab-content.git",
  local_path: Path.expand("../priv/nlab-content", __DIR__),
  branch: "master"

# VintageMachinery client for development
config :droodotfoo, Droodotfoo.Wiki.Ingestion.VintageMachineryClient,
  base_url: "https://vintagemachinery.org",
  local_path: Path.expand("../priv/vintage-machinery", __DIR__),
  rate_limit_ms: 2_000,
  include_paths: ["pubs/", "mfgindex/"]

# MinIO/S3 for development (local MinIO or mock)
config :ex_aws,
  access_key_id: "minioadmin",
  secret_access_key: "minioadmin",
  region: "us-east-1",
  http_client: ExAws.Request.Req

config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: 9000

config :droodotfoo, Droodotfoo.Wiki.Storage,
  bucket_wiki: "droo-wiki",
  bucket_library: "droo-library",
  bucket_backups: "xochimilco-backups"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :droodotfoo, DroodotfooWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "XGb9pKKqaRoHP7mE8lkAi+DHOuhfjGoVhtHmJ8AZ0l6YWLC5GAeZ2u0T9GKKxj5X",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:droodotfoo, ~w(--sourcemap=inline --watch)]},
    npx: [
      "tailwindcss",
      "--input=css/app.css",
      "--output=../priv/static/assets/css/app.css",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :droodotfoo, DroodotfooWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/droodotfoo_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$",
      ~r"priv/resume\.json$",
      ~r"priv/posts/.*\.md$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :droodotfoo, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Spotify configuration (set these in environment variables)
config :droodotfoo, :spotify,
  client_id: System.get_env("SPOTIFY_CLIENT_ID"),
  client_secret: System.get_env("SPOTIFY_CLIENT_SECRET"),
  redirect_uri:
    System.get_env("SPOTIFY_REDIRECT_URI") || "http://localhost:4000/auth/spotify/callback"

# OpenTelemetry: disable tracing in dev by default (set OTEL_EXPORTER=otlp to enable)
config :opentelemetry, traces_exporter: :none
