import Config

# Override esbuild config for production with optimizations
config :esbuild,
  droodotfoo: [
    args: ~w(
      js/app.js
      --bundle
      --target=es2022
      --outdir=../priv/static/assets/js
      --external:/fonts/*
      --external:/images/*
      --minify
      --tree-shaking=true
      --metafile=meta.json
      --drop:console
      --drop:debugger
      --legal-comments=none
      --alias:@=.
    ),
    cd: Path.expand("../assets", __DIR__),
    env: %{
      "NODE_ENV" => "production",
      "NODE_PATH" => Path.expand("../deps", __DIR__)
    }
  ]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :droodotfoo, DroodotfooWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [hsts: true, rewrite_on: [:x_forwarded_proto]]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
