defmodule DroodotfooWeb.Endpoint do
  use Sentry.PlugCapture
  use Phoenix.Endpoint, otp_app: :droodotfoo

  # Session options with secure salts
  # These are baked in at compile time. The salts are used to sign/encrypt
  # session cookies which contain only LiveView state (not sensitive data).
  # Actual secrets (API tokens, etc.) are stored in runtime environment variables.
  @session_options [
    store: :cookie,
    key: "_droodotfoo_key",
    signing_salt: "xK9mPqR2vL8nYw3jH6cT5bN4",
    encryption_salt: "aF7gD1sZ9wE3rQ6yU8iO2pL5",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [session: @session_options],
      check_origin: {__MODULE__, :check_origin, []}
    ],
    longpoll: [
      connect_info: [session: @session_options],
      check_origin: {__MODULE__, :check_origin, []}
    ]

  @allowed_origins [
    "https://droo.foo",
    "https://www.droo.foo",
    "https://droodotfoo-lingering-shadow-740.fly.dev"
  ]

  @doc """
  Validates WebSocket connection origins.
  Production uses explicit allowlist, dev/test allows all origins.
  """
  def check_origin(origin) do
    case Application.get_env(:droodotfoo, :environment, :dev) do
      :prod -> origin in @allowed_origins
      _ -> true
    end
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` and `brotli` options are enabled to serve compressed
  # static files generated by running `phx.digest` and brotli compression.
  #
  # Cache static assets aggressively with versioned filenames (immutable).
  # Assets with digest hashes can be cached forever, others get 1 year.
  plug Plug.Static,
    at: "/",
    from: :droodotfoo,
    gzip: not code_reloading?,
    brotli: not code_reloading?,
    only: DroodotfooWeb.static_paths(),
    headers: %{
      "cache-control" => "public, max-age=31536000, immutable"
    }

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 1_048_576

  plug Sentry.PlugContext
  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DroodotfooWeb.Router
end
