import Config

# Configure your database
config :wiki, Wiki.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "wiki_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Oban queues for development
config :wiki, Oban, queues: [ingestion: 2, images: 4, backups: 1]

# MediaWiki client for development
config :wiki, Wiki.Ingestion.MediaWikiClient,
  base_url: "https://oldschool.runescape.wiki/api.php",
  user_agent: "DrooFoo-WikiMirror/1.0 (https://droo.foo; dev@droo.foo)",
  rate_limit_ms: 1_000

# nLab client for development
config :wiki, Wiki.Ingestion.NLabClient,
  repo_url: "https://github.com/ncatlab/nlab-content.git",
  local_path: Path.expand("../priv/nlab-content", __DIR__),
  branch: "master"

# MinIO/S3 for development (local MinIO or mock)
config :ex_aws,
  access_key_id: "minioadmin",
  secret_access_key: "minioadmin",
  region: "us-east-1"

config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: 9000

config :wiki, Wiki.Storage,
  bucket_wiki: "droo-wiki",
  bucket_library: "droo-library",
  bucket_backups: "xochimilco-backups"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :wiki, WikiWeb.Endpoint,
  # Port 4040 for wiki app (4000 is droodotfoo main app)
  http: [ip: {127, 0, 0, 1}, port: 4040],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "vu9J4YPdUrhDWA9zx9Oq9XvjbFAHWLMx8l3yqx1h7mg7TwMHSlxiRgheQuaMqueP",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:wiki, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:wiki, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :wiki, WikiWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/wiki_web/router\.ex$",
      ~r"lib/wiki_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard
config :wiki, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
